### ISSUE TITLE
CONTRIBUTING.md out of date

### ISSUE THREAD

**Issue by znewton** [AlaskaAirlines/OrionWebCoreStyleSheets#2]
## Problem

1. Does not mention forking the project to make a PR
    - Even though it's common practice on GitHub, it's not universal, especially if the CONTRIBUTING.md explicitly says to do otherwise
2. Has references to the itsals way of doing things in VSTS

## Steps to reproduce

1. Read the CONTRIBUTING.md
2. Realize it's out of date

## Solution

Update to describe desired GitHub process

## Bonus Points

Add PR and Issue templates

**Comment by ecommerceUXdesign** [comment]
Updated: https://github.com/AlaskaAirlines/OrionWebCoreStyleSheets/commit/edd7e0c33c60721605b9e0e9445a5cb2c286ef1f#diff-8cc7b2b0d78dd2501610391c086a8516
