### ISSUE TITLE
img: display block

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/OrionWebCoreStyleSheets#20]
The default css style for images now includes display:block and it is breaking the header footer on pages that use the most up to date version.

![image](https://user-images.githubusercontent.com/5118118/71025071-2fbb5200-20bb-11ea-97cd-3ee362b6ce69.png)

**Comment by blackfalcon** [comment]
Defaults are set to maximize instant use cases. For different use cases, utility classes have been created that will allow for customization on top of the standard defaults. 

In this situation, using the `.util_displayBlock` selector should address the issue. [See more](https://alaskaairlines.github.io/OrionWebCoreStyleSheets/#display-utility-css-.util_displayInlineBlock).

[See full OWCSS docs](https://alaskaairlines.github.io/OrionWebCoreStyleSheets/)

**Comment by blackfalcon** [comment]
With further feedback, the use of the utility class will not address the issues the dev team is encountering. The solution needed is to update docs to better educate users of options when importing Sass selectors as well as remove a default setting for the `img` selector.
