### ISSUE TITLE
Import auro fonts SCSS files complains about missing $asset-font-circular-family-name

### ISSUE THREAD

**Issue by johnvoelk** [AlaskaAirlines/OrionWebCoreStyleSheets#35]
**Describe the bug**
In one of our local SCSS files, attempt to import the fonts and receive the following error:

ERROR in ./src/App.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/App.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable: "$weight-light".
        on line 23 of node_modules/@alaskaairux/orion-web-core-style-sheets/dist/_fonts.scss
        from line 8 of /Users/jvoelk/git/Ryoko/Site/src/App.scss
>>   font-weight: $weight-light;

   ---------------^

**To Reproduce**

- Start webpack to existing React project
- Add the following lines to an SCSS file:
```
@import "~@alaskaairux/orion-design-tokens/dist/tokens/SCSSVariables";
@import "~@alaskaairux/orion-web-core-style-sheets/dist/essentials";
@import "~@alaskaairux/orion-web-core-style-sheets/dist/fonts";
```
- Save the file

**Expected behavior**

Should not have errors.

**Additional context**

If I define the following local variables importing these files is error free:
- $asset-font-circular-family-name: $auro-asset-font-circular-family-name;
- $weight-light: $auro-asset-font-circular-weight-light;
- $weight-book: 400;

**Comment by blackfalcon** [comment]
Yup, this is an issue. The transition from Orion to Auro was done from the perspective that projects would essentially be moving from Orion to Auro. Thus legacy variables would be available. 

This is a hardening case where there is Orion code in WCSS and legacy vars are needed, but not wanted. 

The Sass needs to have a way to detect if the legacy var is available and use it, or if not, use the alternate if available. 

What is needed is something like this

```scss
.foo {
  @if variable-exists(asset-font-circular-family-name) {
    font-family: $asset-font-circular-family-name; 
  } @else {
    font-family: $auro-font-family-default;
  }
}
```

**Comment by blackfalcon** [comment]
This needs to be applied to any reference to a legacy variable, e.g. https://github.com/AlaskaAirlines/OrionWebCoreStyleSheets/blob/master/src/_fonts.scss#L20-L23
